version: "3.4"

services:
    frontend:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                AWS_ACCESS_KEY_ID: '${AWS_ACCESS_KEY_ID}'
                AWS_SECRET_ACCESS_KEY: '${AWS_SECRET_ACCESS_KEY}'
        container_name: bref_frontend
        image: bref_frontend
        working_dir: /var/www/html/app/
        # entrypoint: /bin/bash
        # tty: true
        command: "npm run dev -- --host 0.0.0.0"
        ports:
            - 8000:5173
        volumes:
            - ./:/var/www/html/app
