useDotenv: true
service: bref-frontend

provider:
    name: aws  
    runtime: nodejs14.x
    region: us-east-1
    stage: dev

plugins:
    - serverless-s3-sync

resources:
    Resources:
        # Create our S3 storage bucket using CloudFormation
        S3StaticWebsite:
            Type: AWS::S3::Bucket
            Properties:
                BucketName: ${env:AWS_BUCKET}
                PublicAccessBlockConfiguration:
                    BlockPublicAcls: false
                OwnershipControls:
                    Rules:
                        - ObjectOwnership: ObjectWriter
                WebsiteConfiguration:
                    IndexDocument: index.html
                    ErrorDocument: index.html

    Outputs:
        S3StaticWebsiteOutputName:
            Value: !Ref S3StaticWebsite
        S3StaticWebsiteURL:
            Value:
                Fn::GetAtt: ["S3StaticWebsite", "WebsiteURL"]

custom:
    s3Sync:
        -   bucketName: ${env:AWS_BUCKET}
            localDir: dist
            acl: public-read
            defaultContentType: text/html
            params:
                -   index.html:
                    CacheControl: 'no-cache'
                -   "*.js":
                    CacheControl: 'public, max-age=31536000'